config/routes.rb
Launched::Application.routes.draw do
  resources :portfolios

  resources :props

  resources :projects
    
  resources :comments

  resources :users

  root :to => 'projects#index'

end

app/models/prop.rb
class Prop < ActiveRecord::Base
  attr_accessible :project_id, :user_id

  validates_presence_of :project_id, :user_id
end

app/controllers/props_controller.rb
class PropsController < ApplicationController
  # GET /props
  # GET /props.json
  def index
    @props = Prop.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @props }
    end
  end

  # GET /props/1
  # GET /props/1.json
  def show
    @prop = Prop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @prop }
    end
  end

  # GET /props/new
  # GET /props/new.json
  def new
    @prop = Prop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @prop }
    end
  end

  # GET /props/1/edit
  def edit
    @prop = Prop.find(params[:id])
  end

  # POST /props
  # POST /props.json
  def create
    @prop = Prop.new(params[:prop])

    respond_to do |format|
      if @prop.save
        format.html { redirect_to @prop, notice: 'Prop was successfully created.' }
        format.json { render json: @prop, status: :created, location: @prop }
      else
        format.html { render action: "new" }
        format.json { render json: @prop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /props/1
  # PUT /props/1.json
  def update
    @prop = Prop.find(params[:id])

    respond_to do |format|
      if @prop.update_attributes(params[:prop])
        format.html { redirect_to @prop, notice: 'Prop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @prop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /props/1
  # DELETE /props/1.json
  def destroy
    @prop = Prop.find(params[:id])
    @prop.destroy

    respond_to do |format|
      format.html { redirect_to props_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/props_helper.rb
module PropsHelper
end

app/views/props/_form.html.erb
<%= form_for(@prop) do |f| %>
  <% if @prop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prop.errors.count, "error") %> prohibited this prop from being saved:</h2>

      <ul>
      <% @prop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.number_field :project_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/props/edit.html.erb
<h1>Editing prop</h1>

<%= render 'form' %>

<%= link_to 'Show', @prop %> |
<%= link_to 'Back', props_path %>

app/views/props/index.html.erb
<h1>Listing props</h1>

<table>
  <tr>
    <th>User</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @props.each do |prop| %>
  <tr>
    <td><%= prop.user_id %></td>
    <td><%= prop.project_id %></td>
    <td><%= link_to 'Show', prop %></td>
    <td><%= link_to 'Edit', edit_prop_path(prop) %></td>
    <td><%= link_to 'Destroy', prop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Prop', new_prop_path %>

app/views/props/new.html.erb
<h1>New prop</h1>

<%= render 'form' %>

<%= link_to 'Back', props_path %>

app/views/props/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @prop.user_id %>
</p>

<p>
  <b>Project:</b>
  <%= @prop.project_id %>
</p>


<%= link_to 'Edit', edit_prop_path(@prop) %> |
<%= link_to 'Back', props_path %>