config/routes.rb
Launched::Application.routes.draw do
  resources :portfolios

  resources :props

  resources :projects
    
  resources :comments

  resources :users

  root :to => 'projects#index'

end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  attr_accessible :project_id, :user_id

  validates_presence_of :project_id, :user_id
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  # GET /portfolios
  # GET /portfolios.json
  def index
    @portfolios = Portfolio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @portfolios }
    end
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
    @portfolio = Portfolio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @portfolio }
    end
  end

  # GET /portfolios/new
  # GET /portfolios/new.json
  def new
    @portfolio = Portfolio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @portfolio }
    end
  end

  # GET /portfolios/1/edit
  def edit
    @portfolio = Portfolio.find(params[:id])
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(params[:portfolio])

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render json: @portfolio, status: :created, location: @portfolio }
      else
        format.html { render action: "new" }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /portfolios/1
  # PUT /portfolios/1.json
  def update
    @portfolio = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio.update_attributes(params[:portfolio])
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio = Portfolio.find(params[:id])
    @portfolio.destroy

    respond_to do |format|
      format.html { redirect_to portfolios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio) do |f| %>
  <% if @portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% @portfolio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.number_field :project_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Editing portfolio</h1>

<%= render 'form' %>

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', portfolios_path %>

app/views/portfolios/index.html.erb
<h1>Listing portfolios</h1>

<table>
  <tr>
    <th>User</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @portfolios.each do |portfolio| %>
  <tr>
    <td><%= portfolio.user_id %></td>
    <td><%= portfolio.project_id %></td>
    <td><%= link_to 'Show', portfolio %></td>
    <td><%= link_to 'Edit', edit_portfolio_path(portfolio) %></td>
    <td><%= link_to 'Destroy', portfolio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Portfolio', new_portfolio_path %>

app/views/portfolios/new.html.erb
<h1>New portfolio</h1>

<%= render 'form' %>

<%= link_to 'Back', portfolios_path %>

app/views/portfolios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @portfolio.user_id %>
</p>

<p>
  <b>Project:</b>
  <%= @portfolio.project_id %>
</p>


<%= link_to 'Edit', edit_portfolio_path(@portfolio) %> |
<%= link_to 'Back', portfolios_path %>